export const weatherCodes = {
  0:  { label: 'Clear skies',      icon: '☀️', category: 'clear',     skyTone: 'sunny' },
  1:  { label: 'Mostly clear',     icon: '🌤️', category: 'clear',     skyTone: 'clearing' },
  2:  { label: 'Partly cloudy',    icon: '⛅', category: 'cloudy',    skyTone: 'partlyCloudy' },
  3:  { label: 'Overcast',         icon: '☁️', category: 'cloudy',    skyTone: 'overcast' },
  45: { label: 'Foggy',            icon: '🌫️', category: 'harmattan', skyTone: 'harmattan' },
  48: { label: 'Depositing rime fog', icon: '🌫️', category: 'harmattan', skyTone: 'harmattan' },
  51: { label: 'Light drizzle',    icon: '🌦️', category: 'rain',      skyTone: 'rain' },
  53: { label: 'Moderate drizzle', icon: '🌦️', category: 'rain',      skyTone: 'rain' },
  55: { label: 'Dense drizzle',    icon: '🌧️', category: 'rain',      skyTone: 'rain' },
  56: { label: 'Light freezing drizzle', icon: '🌨️', category: 'rain', skyTone: 'rain' },
  57: { label: 'Dense freezing drizzle', icon: '🌨️', category: 'rain', skyTone: 'rain' },
  61: { label: 'Light rain',       icon: '🌧️', category: 'rain',      skyTone: 'rain' },
  63: { label: 'Moderate rain',    icon: '🌧️', category: 'rain',      skyTone: 'rain' },
  65: { label: 'Heavy rain',       icon: '⛈️', category: 'rain',      skyTone: 'rain' },
  66: { label: 'Light freezing rain', icon: '🌨️', category: 'rain', skyTone: 'rain' },
  67: { label: 'Heavy freezing rain', icon: '🌨️', category: 'rain', skyTone: 'rain' },
  71: { label: 'Light snow',       icon: '🌨️', category: 'rain',      skyTone: 'rain' },
  73: { label: 'Moderate snow',    icon: '❄️', category: 'rain',      skyTone: 'rain' },
  75: { label: 'Heavy snow',       icon: '❄️', category: 'rain',      skyTone: 'rain' },
  77: { label: 'Snow grains',     icon: '🌨️', category: 'rain',      skyTone: 'rain' },
  80: { label: 'Rain showers',     icon: '🌦️', category: 'rain',      skyTone: 'rain' },
  81: { label: 'Moderate rain showers', icon: '🌦️', category: 'rain', skyTone: 'rain' },
  82: { label: 'Violent rain showers', icon: '⛈️', category: 'rain', skyTone: 'rain' },
  85: { label: 'Light snow showers', icon: '🌨️', category: 'rain', skyTone: 'rain' },
  86: { label: 'Heavy snow showers', icon: '❄️', category: 'rain', skyTone: 'rain' },
  95: { label: 'Thunderstorm',     icon: '⛈️', category: 'storm',     skyTone: 'storm' },
  96: { label: 'Storm with hail',  icon: '⛈️', category: 'storm',     skyTone: 'storm' },
  99: { label: 'Storm with heavy hail', icon: '⛈️', category: 'storm', skyTone: 'storm' },
}

export const getWeather = (code) => weatherCodes[code] ?? { label: 'Unknown', icon: '🌡️', category: 'clear', skyTone: 'sunny' }
